version: "3.9"

services:
  db:
    image: circleci/postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: template.env
    environment:
      - CIRCLECI

  web:
    build: .
    command: bash run_dev.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: template.env
    environment:
      - CIRCLECI
      - DJANGO_SECRET_KEY=abc123abc123abc123abc123abc123
